const sampleData = [
  { id: 1, name: 'Harry Potter', author: 'J.K.Rowling', topic: 'Magic' },
  { id: 2, name: 'The lord of the rings', author: 'J.R.R.Tolkien', topic: 'Fantasy'},
  { id: 3, name: 'Sans famille', author: 'Hector Malot', topic: 'Adventure'},
  { id: 4, name: 'Sherlock Holmes', author: 'Conan Doyle', topic: 'Detective'},
  { id: 5, name: 'The old man and the sea', author: 'Ernest Hermingway', topic: 'Classics'},
  { id: 6, name: 'War and peace', author: 'Leo Tolstoy', topic: 'Historical novel'},
  { id: 7, name: 'Harry Potter', author: 'J.K.Rowling', topic: 'Magic' },
  { id: 8, name: 'The lord of the rings', author: 'J.R.R.Tolkien', topic: 'Fantasy'},
  { id: 9, name: 'Sans famille', author: 'Hector Malot', topic: 'Adventure'},
  { id: 10, name: 'Sherlock Holmes', author: 'Conan Doyle', topic: 'Detective'},
  { id: 11, name: 'The old man and the sea', author: 'Ernest Hermingway', topic: 'Classics'},
  { id: 12, name: 'War and peace', author: 'Leo Tolstoy', topic: 'Historical novel'},
  { id: 13, name: 'Harry Potter', author: 'J.K.Rowling', topic: 'Magic' },
  { id: 14, name: 'The lord of the rings', author: 'J.R.R.Tolkien', topic: 'Fantasy'},
  { id: 15, name: 'Sans famille', author: 'Hector Malot', topic: 'Adventure'},
  { id: 16, name: 'Sherlock Holmes', author: 'Conan Doyle', topic: 'Detective'},
  { id: 17, name: 'The old man and the sea', author: 'Ernest Hermingway', topic: 'Classics'},
  { id: 18, name: 'War and peace', author: 'Leo Tolstoy', topic: 'Historical novel'},
  { id: 19, name: 'Harry Potter', author: 'J.K.Rowling', topic: 'Magic' },
  { id: 20, name: 'The lord of the rings', author: 'J.R.R.Tolkien', topic: 'Fantasy'},
  { id: 21, name: 'Sans famille', author: 'Hector Malot', topic: 'Adventure'},
  { id: 22, name: 'Sherlock Holmes', author: 'Conan Doyle', topic: 'Detective'},
  { id: 23, name: 'The old man and the sea', author: 'Ernest Hermingway', topic: 'Classics'},
  { id: 24, name: 'War and peace', author: 'Leo Tolstoy', topic: 'Historical novel'},
  { id: 25, name: 'Harry Potter', author: 'J.K.Rowling', topic: 'Magic' },
  { id: 26, name: 'The lord of the rings', author: 'J.R.R.Tolkien', topic: 'Fantasy'},
  { id: 27, name: 'Sans famille', author: 'Hector Malot', topic: 'Adventure'},
  { id: 28, name: 'Sherlock Holmes', author: 'Conan Doyle', topic: 'Detective'},
  { id: 29, name: 'The old man and the sea', author: 'Ernest Hermingway', topic: 'Classics'},
  { id: 30, name: 'War and peace', author: 'Leo Tolstoy', topic: 'Historical novel'}
];

export default sampleData;